:idprefix:
:idseparator: -
:imagesdir: ../../images

:onecx_docs_repo_link:     link:https://github.com/onecx/docs[OneCX Docs]

= OneCX Docs: Set up Local Environment

To preview and test your documentation changes locally, set up the documentation environment as following:

== Get and Build the Docs

. Clone the {onecx_docs_repo_link}
+
[source,bash]
----
git clone git@github.com:onecx/docs.git
----

. Go to `Docs` directory.

. Install Node Modules
+
[source,bash]
----
node install
----

. Create Docs Site
+
[source,bash]
----
npx antora antora-playbook.yml 2> site.log
----
+
`site.log` contains the log output of the build process. Check it for errors.

. Open Build Result in Browser
+
[source,bash]
----
./build/site/index.html
----


== Integrate a local Module

. Create a local Copy of Antora Playbook
+
[source,bash]
----
cp antora-playbook.yml antora-playbook.local.yml
----

. Use the local Module Path in the local Antora Playbook
+
In this example, the local path `/home/henry/onecx/docs/docs-guides-ui` is used instead of the remote URL for the `docs-guides-ui` module.
+
[source,yaml]
----
    #- url: https://github.com/onecx/docs-guides-ui.git
    - url: /home/henry/onecx/docs/docs-guides-ui
      branches: [HEAD]
      start_path: docs
----

. Create Docs site with local Module
+
[source,bash]
----
npx antora antora-playbook.local.yml 2> site.log
----

[NOTE]
====
* Make sure to check the `site.log` file for errors during the build process.
** Search for entries related to your local module.
** Ignore entries about Quarkus and BFF if not relevant.
* If you add new modules, verify the navigation structure in the built site.
====


== Development Support

* Use AsciiDoc plugin in your IDE for syntax highlighting and preview.
* Check the log output after building the website to identify issues.

