:idprefix:
:idseparator: -
:imagesdir: ../../images

:onecx_local_env_docs_ref:     xref:documentation:onecx-local-env:index.adoc[OneCX Local Environment]
:onecx_docs_guideline_ref:     xref:./docs_guidelines.adoc[OneCX Documentation Guidelines]
:onecx_docs_setup_ref:         xref:./docs_setup.adoc[OneCX Docs: Local Setup]
:onecx_docs_formatting_ref:    xref:./docs_formatting.adoc[OneCX Docs: Formatting]
:onecx_docs_writing_style_ref: xref:./docs_writing_style.adoc[OneCX Docs: Writing Style]
:antora_doc_link:              link:https://docs.antora.org/antora/latest/[Antora]
:asciidoc_doc_link:            link:https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoc]


= OneCX Documentation

Welcome to the OneCX documentation hub for contributors and users.
This page is your entry point to the guides, conventions, and tooling
used to write and publish OneCX documentation.

== Purpose
The goal of this guide is to keep documentation simple, consistent
and easy to maintain across the OneCX ecosystem.
We author content in {asciidoc_doc_link} and publish sites using {antora_doc_link}.


== Guidelines and Styling
* Follow the guidelines in {onecx_docs_guideline_ref}.
* For writing style guidelines, see {onecx_docs_writing_style_ref}.


== Getting Started
To set up your local environment for writing and previewing OneCX documentation, follow the instructions in {onecx_docs_setup_ref}.


== Formatting & Conventions
For formatting and conventions used in OneCX documentation, see {onecx_docs_formatting_ref}.


== Reference
See the {onecx_local_env_docs_ref} - it is our reference implementation for structure, style and conventions.

