:imagesdir: ../images
= OneCX Documentation

:idprefix:
:idseparator: -

:guides_url: xref:latest@guides:general:index.adoc

[#introduction]
== Introduction
OneCX is a platform that allows projects to easily build systems with microservice and microfrontend architecture and utilize the advantage of those architectures in regards of scales agile development. The platform offers various assets which can be leveraged to have a quick project ramp-up and a high speed of development without losing the flexibility of a custom developed solution.

Some of these assets are:

* Development guidelines for the teams 
* Build in security and multitenancy 
* Build in client-side integration of microfrontends which support all major SPA frameworks e.g. angular, react 
* Reference implementation of cross-cutting system features including administrative UIs (e.g. user and permission management) which can be used to quickly ramp up a system and can be exchanged later if needed 

[#documentation-overview]
== Documentation overview
To get familiar with OneCX technical information, refer to the following content:

* xref:index.adoc[Introduction]
* xref:architecture-overview/index.adoc[Architecture overview]
** xref:architecture-overview/frontend.adoc[Frontend]
** xref:architecture-overview/bff.adoc[Backend-for-frontend]
** xref:architecture-overview/backend.adoc[Backend]
** xref:architecture-overview/ci.adoc[CI]
** xref:architecture-overview/cd.adoc[CD]
