:idprefix:
:idseparator: -

= Migrate OneCX Shell from v2 to v3

==  Overview
This document provides changes that need to be done to migrate from OneCX Shell v2 to v3. 
Provide Changes

== Migration Steps

=== Slot

=== Module Federation Approach Changes
Document @module-federation/enchanced recommended usage and legacy @angular-architects usage
    Document how to build apps using new module federation approach:

    using @nx/angular/module-federation (uses @module-federation/enchanced)
    using @module-federation/enchanced
    using @angular-architects (adding shareScope key to existing configuration)
    Acceptance criteria:

    all solutions are presented as examples
    it is recommended to use build tools that base on @module-federation/enchanced from shell v3
    it is required to add share scope keys from angular 21

=== Exposing mf-manifest.json file
    With @module-federation/enchanced used for building the app it should be recommended to use mf-manifest.json file.
    Acceptance criteria:
    change is recommended and example values.yaml is presented

== Supported Angular/React Versions




