= OneCX Architecture Overview

== Overview
// TODO: Mention mulit-tenancy
OneCX is a platform that allows users to dynamically adjust displayed content of their pages. In order to achive this goal OneCX is offering complete applications with user-friendly interfaces that enable its users to completely change the way their content is displayed during the runtime. These applications allow users to change assigned permissions, color palette of most of the displayed content, change menus and many more. Apart from the applications offered by OneCX, users can create all sorts of applications and dynamically add them to their workspace using our platform without the need to stop any already running functionalities.

To make such platform work, we prepared a solution in which many applications co-exist and work with eachother. OneCX architecture can be divided into the following sections:

// TODO: Add identity provider info
* **Shell**: An application responsible for rendering the platform overlay and displaying content using workspace and user information via registered applications with microfrontends. More about the shell can be found xref:architecture-overview/shell.adoc[here].
* **Applications/Microfrontends**: A microfrontend is the part of the application that serves user interface for a single domain. It is completely independent from other microfrontends hence the name. An application however, is a complete bundle of every resource that is needed for microfrontend to work properly. For OneCX core applications those resources will be backend microservices and databases which are used for storing, reading and manipulating the data. More about microfrontends can be found xref:architecture-overview/mfe.adoc[here].
* **Remote components**: A remote component is similar to microfrontend when it comes to its purpose. They are relatively small pieces of UI rendered on the platform that can be managed dynamically. They come in handy in situations where many applications could use the same component related to an application (ex. many applications might want to use component related to permission management) or when a piece of content could be changed depending on the used workspace. More about remote component can be found xref:architecture-overview/remoteComponents.adoc[here].
* **Identity provider**: TODO

== OneCX core applications
Shell is considered as one of the core applications in the OneCX platform architecture. Since no mcirofrontend or remote component can be displayed without the shell application, it is the most important one. In order to serve correct content it needs to cooperate with other core applications, which are responsible for different parts of platform management. Those applications are:

// TODO: Add tenant info
* **Workspace** - Manages **workspaces** by enabling configuration of registered applications and components, menus and every data related to **what can be seen in a given workspace**.
* **Product Store** - Manages **applications** by enabling removal, edition and registration of applications on the platform. Those **applications can then be assigned to be used by workspaces**.
* **Theme** - Manages **themes** (page color palette and other style adjustments) that can be selected by workspaces to change **how content is displayed in a given workspace**.
* **Permission** - Manages **permissions** via permission-role assignments by enabling addition and removal of permission from a given role to determine **what content can be seen or be interacted with by a user with given role**.
* **User Profile** - Manages **users** via personal information associated to a user and other information important for platform display (ex. user's locale to display content using correct language) to **ensure content is displayed aligned with user preferences** 
* **Tenant** - Manages tenancy TODO

== Knowledge base
// TODO: Add links to:
// TODO: External microfrontend idea explanation paper
// TODO: External guide to mfe and remote component dev with angular
Before getting into the details of the OneCX platform it is useful to get familiar with the following concepts:

* **Microfrontend idea** - TODO
* **OneCX microfrontend with angular** - TODO(INTERNAL)
* **OneCX remote component with angular** - TODO(INTERNAL)
// TODO: Add list item for every core product and auth guide?

