= OneCX Microfrontends

== Overview
Microfrontend is a part of the application that serves user interface for a single domain. It is independent from all other microfrontends and can represent any content it needs, however it must integrate with shell application. Shell is a special application, which is responsible for determining what microfrontend to display on a given route on the page. A single microfrontend can be any size depending on your needs, however it should be focusing on a single domain (similar to microservices, hence the name).

In the OneCX platform every core application has its own microfrontend (apart from shell, where its user interface is considered as a host for all other microfrontends). Their purpose is to allow our platform users to easily configure their workspaces.

== Why microfrontends?
The main adventage of using approach with microfrontends is that you can create many independent applications and workspaces which will use only those that are important for it, without the need to change anything in the application code. With the usage of OneCX core applications you can configure your workspaces without the need to write any code apart from your business use case user interfaces and services.

== Application vs Microfrontend
When discussing xref:architecture-overview/index.adoc[OneCX Architecture], we briefly touched the topic of Application vs Microfrontend, but its important to know the difference between those two concepts.

From OneCX platform perspective the only important piece of software is the exposed frontend application (microfrontend). It means that none of the OneCX architecture elements takes the services that your microfrontend uses into consideration (ex. a backend to handle storing data in a database), so it is all up to you when it comes to the logic behind your microfrontend. Your application does not even need any backend services as long as it is exposing a frontend application that OneCX platform can use.

== How does the microfrontend integrate with Shell?

// TODO: add link to shell where microfrontend loading is explained
// TODO: link to resoucres
Microfrontends are services which are exposing a file, used by the shell application to correctly load and display its content on a page. Those files contain application code and all information neccessary to render microfrontend's content. Your micrforontend can represent whatever you want and the only requirement is to ensure correct configuration in order to load it correctly within the shell. Microfrontend loading done by the shell is explained here(TODO). If you want to know more about how to expose your frontend application and all the details behind what is exposed, please refer to resource list(TODO) at the end of the page.


// TODO: Instead of explaining what to do, add a link to documentation page that does that and explain only what happens when you register mfe

== Microfrontend registration
// TODO: Explain what to do to correctly register microfrontend and what happens when you do that

== Microfrontend usage
// TODO: Explain what to do to use microfrontend in the workspace and what happens when you do that

== Microfrontend example using Angular
// TODO: Put example on how to configure microfrontend in angular?

== Useful resources
* **Expose your microfrontend with webpack** - TODO
* **Expose your microfrontend with module federation** - TODO
* **Microfrontend idea** - TODO
* **OneCX microfrontend with angular** - TODO(INTERNAL)

