= OneCX Microfrontends

== Overview
A Microfrontend is a OneCX App, often considered as a UI App, which is a part of the OneCX Application. It is responsible for exposing a piece of user interface via remote entry file that can be used by other UI applications. The difference between the standard UI application and a microfrontend is that Microfrontend is never accessed directly.

== Why Microfrontends
To precisely explain the purpose of using Microfrontends, it is crucial to become familiar with the client side of each Microfrontend.

=== Microfrontend clients
As previously stated, each Microfrontend is exposing a remote entry file, that can be accessed by any application. This remote entry file should contain all the data required to display the desired pieces of user interface. In the context of OneCX platform, this file is accessed and used in one of those situations:
* **Module display**: Shell Application during workspace construction creates routing rules and associates a remote entry file with a specific route. Whenever user navigates to that route remote entry file is used (with other data of the current workspace) to display desired module in the content pane of the page.
* **Remote Component display**: Any of Microfrontend's module, Remote Component or Shell Application in any period during platform runtime uses remote entry file to display a piece of user interface within a page.

// TODO: Add link to remote components
Module display is suited for whole UI modules, which consists of many pages and its own routing rules, whereas Remote Components are suited for smaller pieces of UI, which can be easily replacable and reusable within the platform. It is important to know that **Remote Components and Modules are both exposed via Microfrontend through a remote entry file**. More on the topic of Remote Components can be found here(TODO).

=== Scaled agile
The main reason of using approach with microfrontends is to allow teams to develop user interfaces in a scaled agile manner. It is best suited for large organisations that want to create user interfaces using many independent teams. In such cases, it is not possible, to develop an UI monolith application efficiently. With the Microfrontends approach, OneCX platform is delivering a solution to allow those teams to work on their own pieces of user interfaces, while preserving a common ground and allowing to easily integrate with eachother.

In OneCX platform context, a Microfrontend is part of the Application which can be integrated using OneCX Core Applications in matter of seconds and customized depending on the users needs. Each Microfrontend is independent from others and can be responsible for a subset of the functionalities needed for the organization. The technical details of the displayed content within a Module or Remote Component exposed via Microfrontend are only relevant for the developers responsible for that Application.

== Exposing user interfaces
//TODO: Link to angular-architects
//TODO: Link to onecx guide for webComponents
The mechanism of displaying Microfrontend's content dynamically is related to how its content is exposed. In OneCX platform context, there are 2 methods of displaying Microfrontend's content:
* **Angular**: Angular components and modules are exposed.
* **Webcomponent**: Components and modules are wrapped as webcomponents then exposed.

**It is NOT recommended** to use Angular method. Doing so restraints the platform from using many frameworks with different versions, which means that all Microfrontends would need to use the same technology and version.

// TODO: Link resources
== Useful resources
* Microfrontend idea
* module-federation
* webcomponents
* OneCX Microfrontend with angular

