= OneCX Shell

== Overview
OneCX Shell is the heart of the OneCX platform. It's the most important OneCX core application that glues together all applications and makes the platform seems like a single page application. Without the shell running, there will be nothing for users to use.

[[application_bundle]]
== Application bundle
Below is a list of apps the shell application consists of:

include::partial$shell-bundle.adoc[]

== Application responsibilities
The Shell application is a special case of OneCX application. It is a host for Microfrontends in the platform. The list of its responsibilities is the following:

* client-side workspace construction
* routing and remotes loading
* workspace and user data sharing

=== Client-side workspace construction
OneCX platform is operating on the idea of workspaces. Each workspace can have many applications registered and can be customized to its users' needs via custom menu configuration, page theming and many more possibilities. To construct a valid workspace, the following operations happen:

1. Shell BFF gathers workspace information. Data required to construct a valid workspace to function on the platform is saved in several databases. These can be reached using SVCs of OneCX core applications. Shell BFF connects with them and gathers all required information in a single response.
2. Shell UI constructs routing rules for a given workspace based on the data fetched by Shell BFF.

=== Routing and remotes loading
// TODO: Add module federation link 
When Shell UI is finished with workspace construction, its next responsibility is to react to routing changes and load Microfrontends's exposed modules into the page. To achieve that, Shell UI app is using Module Federation, which allows to dynamically load remote entries at runtime and display them in the host app. In this way, on a valid routing operation Shell UI app will load the exposed Microfrontend's module and display it in the content pane of the page.

=== Workspace and user data sharing
// TOOD: Add link to topic
When Shell UI app receives the workspace and current user data from the backend, it makes sure that this data is available for any Microfrontend's content. This data is passed on by the Shell UI app to Topics.

A Topic is a similar concept to that of an Observable, but it can be used to pass data between the apps using browser memory. It is a concept implemented in OneCX via `@onecx/integration-interface`. A more in-depth explanation on it can be found here(TODO). For Angular based Microfrontends, services in the `@onecx/angular-integration-interface` package might be useful during the development. They are operating on Topics which contain information passed along by the Shell UI app.

Having data persist in browser memory via Topics gives Microfrontend's content direct access to information about the workspace and current user. Information passed on by the Shell UI app contains the following information:

* details of current workspace 
* Remote Components and slots registered for current the workspace
* the current user's personal information
* the current user's settings (such as language or locale)
* the current user's permissions
* currently accessed Microfrontend data (information available after Microfrontend gets loaded)

Any Microfrontend's content can then utilize this data and act on it with the possibility to react to data changes.

// TODO: Link resources
== Useful resources
* xref:architecture-overview/index.adoc[Architecture overview]
* xref:architecture-overview/mfe.adoc[Microfrontends]
* xref:architecture-overview/remoteComponents.adoc[Remote Components]
* @onecx/integration-interface
* @onecx/angular-integration-interface
* module-federation
