= OneCX Shell

== Overview
OneCX Shell is the heart of the OneCX platform. It's the most important OneCX core application that glues together all applications and makes the platform seems like a single page application. Without the shell running, there will be nothing for users to use.

[[application_bundle]]
== Application bundle
Below is a list of apps that shell application consists of:

include::partial$shell-bundle.adoc[]

== Application responsibilities
Shell application is a special case of OneCX application. It is a host for microfrontends and remote components in the platform. The list of its responsibilities is the following:

* client-side workspace construction
* routing and remotes loading
* workspace and user data sharing

=== Client-side workspace construction
OneCX platform is operating on the idea of workspaces. Each workspace can have many applications registered and can be customized to its users needs via custom menu configuration, page theming and many more possibilities. To construct a valid workspace the following operations happen:

1. Shell BFF gathers workspace information. Data required to construct a valid workspace to function on the platform is saved in several databases which can be reached using SVCs of OneCX core applications. Shell BFF connects with them and gethers all required information in a single response
2. Shell UI constructs routing rules for a given workspace based on the data fetched by Shell BFF

=== Routing and remotes loading
// TODO: Add module federation link 
When Shell UI is finished with workspace construction, its next responsibility is to react to routing changes and load microfrontends into the page. To achive that, shell UI app is using module federation, which allows to dynamically load remote entries on the runtime and display them in the host app. This way on a valid routing operation shell UI app will load the exposed microfrontend's content and display in the content pane of the page.

=== Workspace and user data sharing
// TOOD: Add link to topic
When Shell UI app receives the workspace and current user data from the backend, it makes sure that this data is available for any microfrontend or remote component. This data is passed on by the Shell UI app to topics.

Topic is similar concept to observable, but it can be used to pass data between the apps using browser memory. It is a concept implemented in OneCX via `@onecx/integration-interface` and more in depth explanation on it can be found here(TODO). If you use or intend to use Angular as your microfrontend or remote component technology, then in `@onecx/angular-integration-interface` package you can find services, which can be useful to use since they are operating on topics which contain information passed along by the shell UI app.

Having data persisted in browser memory via topics gives microfrontends and remote components direct access to information about the workspace and current user. Information passed by the shell UI app contains the following information:

* details of current workspace 
* remote components and slots register for current workspace
* personal information of current user 
* settings of current user (such as language or locale)
* permissions of current user
* currently accessed microfrontend data (information after microfrontend gets loaded)

Any microfrontend or remote component can then utilize this data and act on it with a possibility to react on data changes.

== Useful resources
* xref:architecture-overview/index.adoc[Architecture overview]
* xref:architecture-overview/mfe.adoc[Microfrontends]
* xref:architecture-overview/remoteComponents.adoc[Remote components]
* @onecx/integration-interface
* @onecx/angular-integration-interface
