= Microfrontend Content loading in OneCX

== Microfrontend's content loading explained
When discussing Microfrontend loading mechanisms there are 2 important factors that decide on how loading mechanism work. Those factors are:

* **content type**
** Module
** Remote Component
* **expose method**
** Angular
** Webcomponent

NOTE: OneCX platform uses **module-federation** technology integrated with **Webpack** to expose and load Microfrontends. To find out more about how module-federation enables microfrontends, please refer https://www.angulararchitects.io/en/blog/the-microfrontend-revolution-module-federation-in-webpack-5/[here]

=== Content type
In the context of content loading, content type **determines which mechanism will be responsible for loading**. Module loading will be handled by the Shell UI router via constructed routing rules and Remote Component loading will be handled by the Slot Component (to which the Remote Component has been assigned).

==== Shell UI router mechanism (Module)
When dealing with modules, Shell UI is responsible for loading them. As explained in the xref:architecture-overview/shell.adoc[Shell overview], Shell UI first constructs workspace and then handles routing and loading of remotes. Workspace configuration contains all valid routes to Applications registered for a given workspace, each route associated with a Microfrontend's module.

Prior to any routing events, Shell UI initializes router to reflect workspace configuration. Based on the data from backend services about the current workspace, Shell UI creates routing rules to use during the runtime.

Let's take a workspace using user management Application as an example. Each Application in workspace configuration has to have a path defined. This path is used for routing and accessing remote entry file of Application Microfrontend. Assuming the path is `/user`, Shell UI will create a routing rule specifying that whenever url of the page changes to one starting with `/user` it has to load the Microfrontend's module associated with user management Application.

After routing rules are successfully created, each registered Application should have a Route registered in Shell UI's router. Each Route has a **loadChildren method, which called whenever route gets activated** and other properties used for route matching.

The **loadChildren method is responsible for loading the remote module into the Shell UI's memory using module-federation**. When remote module is loaded successfully, it is used by the router to display module's content a page content pane.

==== Slot Component mechanism (Remote Component)
Remote Component loading is handled by Slot Component. Overall mechanism of Remote Components loading was explained in the xref:architecture-overview/remoteComponents.adoc[Remote Components documentation]. In the context of content loading its important to note the following aspects:

* Remote Component **loading process starts when Slot Component is rendered** on a page
* Remote Component **exposed content is loaded via module-federation** (similar to module content type). Then once its loaded successfully, it is **rendered onto a page within the Slot Component via dynamic content creation mechanism dependent on the chosen expose method**

=== Expose method
Expose method is a factor that is taken into consideration by the respective loading mechanism (Shell UI router or Slot Component) to ensure correct content loading of the content. For module loading, the loadChildren method and router configuration is impacted. For Remote Component loading, different mechanism of dynamic content creation is chosen. For information on specific expose method impacts, please refer to the following documents:

* xref:implementation-details/mfe-content-loading/webcomponents.adoc[Webcomponent method]

== Useful resources
* xref:architecture-overview/shell.adoc[Shell overview]
* xref:architecture-overview/remoteComponents.adoc[Remote Components]