= Web Components in OneCX

== Overview
Web Components is a suite of different technologies used to create reusable custom elements with encapsulated functionality. In OneCX context they are usefull for dynamic content creation for both modules and Remote Components display of Microfrontends. Prior to reading this document it is recommended to read the documentation of xref:implementation-details/mfe-content-loading/index.adoc[microfrontend content loading] to get familiar with the content loading mechanisms available within the OneCX platform. 

IMPORTANT: Webcomponent expose method enables the OneCX platform to use UI Apps developed with different frameworks and versions. It is the **recommended method for all Applications**.

NOTE: Web Components technologies are used within OneCX platform, however OneCX offers its own functionalities that should be used to expose Microfrontend's content using the webcomponent method. Those functionalities are based on Web Components technologies, so there is no need to get familiar with them. Nevertheless, more resources about Web Components can be found https://developer.mozilla.org/en-US/docs/Web/API/Web_components[here]

== Web Components preview
Web Components are used in OneCX context for dynamic content creation. OneCX platform uses Web Components technologies to bound UI components to html elements. OneCX platform will use information from Application Store to determine what html elements have to be rendered to display certain modules and Remote Components. Then, during module or Remote Component creation, OneCX platform will load their content and create specified html elements without directly projecting loaded content onto a page.

In summary, with webcomponents method OneCX platform is only loading the code required for Microfrontend's content into the Shell UI memory and creating a "host" element for Remote Components or modules to attach into using Web Components.

For this method to work 2 requirements needs to be fullfield:

. Database is correctly configured for module or Remote Component
.. technology set to WebComponent
.. tag name set to agreed html element name
. Microfrontend is adapted to expose Web Components compliant content
.. component needs to be registered as Custom Element in Custom Elements Registry of Web Components
.. angular issues are covered (use `@onecx/angular-webcomponents` library to cover them by default)
... ngZone sharing
... platform sharing
... router

NOTE: Database configuration is easy to set up using the Application Store Application.

IMPORTANT: To ensure Microfrontend compliance with Web Components for Angular modules and Remote Components it is recommended to use `@onecx/angular-webcomponents` library.

// TODO: Link to guide of webcomponents expose method 
== Expose Microfrontend's content as Web Components
OneCX platform offers different ways of xref:architecture-overview/mfe.adoc[exposing Microfrontend's content]. One of them is **webcomponent method**.

When exposing modules with webcomponents method, it is required to ensure the correct setup. For exposing Angular modules there are functionalities provided via `@onecx/angular-webcomponents` library. For detailed guide on how to expose Microfrontend via webcomponents method, please refer here.

// TODO: Explain that component is registered in Custom Elements Registry

// TODO: Say that those issues are Angular related
// TODO: Say that those issues are covered if you use `@onecx/angular-webcomponents`

// TODO: Explain ngZone and platform sharing
// TODO: ^ Add link to module-federation docs on this issues
// TODO: Multiple router issues

== Web Components in OneCX
As stated in xref:implementation-details/mfe-content-loading/index.adoc[Microfrontend content loading documentation], every method of Microfrontend's content exposal has an impact on the OneCX platform behavior for both module and Remote Component loading.

// TODO: Add link to example of migrating angular modules to integrate with OneCX
=== Module loading behavior
Shell UI App is responsible for displaying Microfrontend's module when router navigation is matched for a desired Microfrontend. With webcomponent method Shell UI will adapt the loadChildren method to:

// TODO: Say loader module is loaded instead which is only creating the html element after module load
// TOOD: Say that for angular method the loaded module is used as return to loadChildren
. load desired remote module via module-federation's loading functionality
. load WebComponentLoaderModule instead of 

// TODO: Add link to example of migrating angular remote components to integrate with OneCX
=== Remote Component behavior

// TODO: Say that for angular method viewContainer is used to render component
// TODO: Say that for web components slot is appending an html element directly below itself so remote component can attach there

// TODO: Explain how web components are utilized in OneCX for both modules and remote components
// TODO: Explain additional modifications needed to be done by modules/remote-components to make them work 
