ifdef::env-site[]
include::partial$_attributes.adoc[]
endif::[]
:imagesdir: ../images

= Creating a OneCX Application

This guide walks you through the process of creating a simple OneCX Application using the OneCX App Generator and integrating it into your local OneCX environment.

What is a OneCX Application?::
A OneCX Application is a set of microfrontends and services that together provide specific functionality within the OneCX platform. It typically consists of a user interface (a microfrontend) and backend services that support its operations. A OneCX Application is designed to be modular, scalable, and easily integrable with other applications within the OneCX ecosystem.
+
.See also:
* {onecx_docs_overview_app_ref} provides more information about the concept of OneCX Applications.
* {onecx_docs_apps_ref} for a list of existing OneCX Applications with details.


== Prerequisites
Before you begin, ensure you have the following prerequisites in place:

* A working OneCX Local Environment set up. If you haven't done this yet, follow the instructions in the {onecx_local_env_setup_ref}.
* Node.js, npm, nx installed on your development machine.
* Familiarity with Angular, as the microfrontends in OneCX are typically built using this framework.
* Access to the OneCX App Generator. You can find it in the {onecx_app_generator_ref}. +
  Install it globally or use npx to run it without installation.
* Get and prepare the OneCX App Generator:
** The *onecx-nx-plugins* repository needs to be cloned into a folder on the local machine/inside WSL2.
+
[source,bash]
----
git clone https://github.com/onecx/onecx-nx-plugins.git
----
** Navigate into the cloned repository and install the dependencies:
+
[source,bash]
----
cd onecx-nx-plugins
npm install
----
** Build the OneCX App Generator:
+
[source,bash]
----
npm run build
----



== Lets go!
In this tutorial, we will create a simple OneCX application called "Hello World" that displays a welcome message to users. To illustrate the basic application concept, this application consists of the following components.

.Application Components
. *onecx-hello-world-ui* => Microfrontend +
  The user interface (UI) component that displays the welcome message.
. *onecx-hello-world-bff* => Microservice +
  Backend For Frontend (BFF) service that handles any backend logic required by the UI.
. *onecx-hello-world-svc* => Microservice +
  Backend Service (SVC): A simple service that could be used to log visits to the application (optional for this basic example).


=== Step 1: Generate Application
. Open a terminal and navigate to the directory where you want to create your OneCX Application.
. Run the OneCX App Generator command:
+
.Create a new OneCX application using the ngrx template:
[source, bash]
----
npx @onecx/create-workspace ngrx hello-world
----
. Follow the prompts to provide details about your application, such as its name, description, and any specific configurations you want to include.
. Once the generation process is complete, navigate into your new application's directory:
+
[source, bash]
----
cd hello-world
----