= OneCX Documentation

== Introduction
// TODO: Add ref to developer docs
This documentation aims to explain the technical details of the OneCX architecture. Although, some code snippets and examples will be presented, it is **NOT** a guide on how to develop applications using OneCX. For such resources, please refer to TODO. If you desire to gather some in depth information on how our solution enables you to create applications with easily replacable components and dynamically change displayed content in your user interfaces, you are in the right place.

== Documentation overview
To get familiar with OneCX technical information refer to the following content:

* xref:index.adoc[Introduction]
* xref:architecture-overview/index.adoc[Architecture overview]
** xref:architecture-overview/shell.adoc[Shell]
** xref:architecture-overview/mfe.adoc[Microfrontends]
** xref:architecture-overview/remoteComponents.adoc[Remote components]
* xref:implementation-details/index.adoc[Implementation details]
** xref:implementation-details/webcomponents.adoc[Webcomponents]