= OneCX Local Environment
:local-env-url: https://github.com/onecx/onecx-local-env?tab=readme-ov-file#onecx-local-environment-setup

== Overview
With the OneCX platform, every application needs to be adjusted for integration within the platform. For the best experience with Application development and integration, OneCX offers a {local-env-url}[OneCX Local Environment] repository. It provides a consistent setup of the platform and Core Applications with minimal actions and allows extension.

== Setting Up OneCX and Core Applications
Using {local-env-url}[OneCX Local Environment] repository allows to:

* set up all required services to run the OneCX platform
* set up Shell and other Core Applications with preconfigured data
* develop and test Applications that are already integrated with the platform
* easily extend and overwrite the configuration of the platform and Applications

=== Prerequisites
It is recommended to get familiar with the README of the {local-env-url}[OneCX Local Environment] repository to make sure the machine's configuration meets the expectations. It is important to follow it cautiously. Assuming all the steps have been completed, it should be possible to access the OneCX platform locally with preconfigured Shell and Core Applications.

=== Local Development
// TODO: Link to standalone
// TODO: Link to sharing packages, webpack?
While it is possible to develop Applications in isolation or in standalone mode, it is recommended to always develop using the {local-env-url}[OneCX Local Environment]. It is the closest configuration to the one in production that utilizes Webpack configuration and the Microfrontends approach and does not require any additional setup to ensure correct integration with OneCX platform.

{local-env-url}[OneCX Local Environment] repository offers several approaches on how to set up Applications for local development, allowing different possibilities.

=== Extending The Environment
// TODO: This part is not documented well on local-env
The {local-env-url}[OneCX Local Environment] repository already takes care of the base configuration for the Shell and Core Applications. By modifying the contents of `imports` and `init-data` directories, it is possible to tune the platform by including additional data for Core Applications or adding data for new ones. It is particularly useful for maintaining platform consistency among team members and reverting to the default state whenever needed.
